services:
  - type: web
    name: fastapi-backend
    env: python
    repo: https://github.com/eat3torice/myproject
    branch: main
    buildCommand: pip install -r backend/app/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        value: your_database_url
