services:
  - type: web
    name: fastapi-backend
    env: python
    repo: https://github.com/eat3torice/myproject
    branch: main
    buildCommand: pip install -r backend/app/requirements.txt
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        value: your_database_url

  - type: web
    name: react-frontend
    env: static
    repo: https://github.com/eat3torice/myproject
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://fastapi-backend.onrender.com

